version: '3.8'

services:
  web_wsp_yb:
    build: .
    # ports:
    #   - "5000:5000"
    command: python main.py
    expose:
      - 95
    volumes:
      - ./app:/app/
    environment:
      - SERVER_HOST=mysqldb_mariadb_1

  nginx_wsp_3:
    image: nginx:latest
    restart: always
    ports:
      - "142:80"
    environment:
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=wsp-yb.santiagofiltros.cl
      - LETSENCRYPT_HOST=wsp-yb.santiagofiltros.cl
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web_wsp_yb

networks:
  default:
    name: web_private_red_webapps #dbs_red_db
    external: true